captainVersion: '4'
services:
    $$cap_appname:
        image: index.docker.io/marcopeg/docker-vacuum:$$cap_docker_vacuum_version
        notExposeAsWebApp: 'true'
        environment:
            LOG_LEVEL: $$cap_log_level
            VACUUM_DELAY: $$cap_vacuum_delay
            VACUUM_INTERVAL: $$cap_vacuum_interval
            VACUUM_RULES: $$cap_vacuum_rules
            VACUUM_SYSTEM_PRUNE: $$cap_vacuum_system_prune
            VACUUM_SYSTEM_PRUNE_VOLUMES: $$cap_vacuum_system_prune_volumes
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        caproverExtra:
            containerHttpPort: '80'
caproverOneClickApp:
    variables:
        - id: $$cap_docker_vacuum_version
          label: Docker Vacuum Version
          defaultValue: 'latest'
          description: Select the version of Docker Vacuum to deploy. Check Docker Hub for available tags.
        - id: $$cap_log_level
          label: Log Level
          defaultValue: 'info'
          description: Sets the log level for Docker Vacuum.
        - id: $$cap_vacuum_delay
          label: Initial Delay
          defaultValue: '600000'
          description: Delay in milliseconds to the first cleanup run after the container has started.
        - id: $$cap_vacuum_interval
          label: Cleanup Interval
          defaultValue: '600000'
          description: Interval in milliseconds between cleanup runs.
        - id: $$cap_vacuum_rules
          label: Cleanup Rules
          defaultValue: '[{\"match\":\"(.*)\",\"retain\":2}]'
          description: JSON formatted rules defining how many old images to retain.
        - id: $$cap_vacuum_system_prune
          label: System Prune
          defaultValue: 'false'
          description: Enable or disable Docker system pruning.
        - id: $$cap_vacuum_system_prune_volumes
          label: Prune Volumes
          defaultValue: 'false'
          description: Enable or disable pruning of Docker volumes.
    instructions:
        start: Docker Vacuum helps manage and clean up Docker environments automatically. Please configure the environment variables as needed.
        end: Docker Vacuum is now configured and will start automatically. Please ensure all settings are correctly configured.
    displayName: Docker Vacuum
    isOfficial: false
    description: Automated Docker cleanup tool to manage Docker environments efficiently. Extensible and easy to set up.
    documentation: 'https://github.com/marcopeg/docker-vacuum'
